apiVersion: v1
kind: Secret
metadata:
  name: ""
type: Opaque
data:
  AWS_WP_BUCKET_KEY: ""
  AWS_WP_BUCKET_SECRET: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ""
data:
  AWS_WP_BUCKET: ""
